steps:
# Step 1: Build the Spring Boot application
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package', '-DskipTests']

# Step 2: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/googlegenai:$COMMIT_SHA', '.']

# Step 3: Push the Docker image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/googlegenai:$COMMIT_SHA']

# Step 4: Deploy the Docker image to Cloud Run (or any other GCP service)
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'googlegenai', '--image', 'gcr.io/$PROJECT_ID/googlegenai:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed']
