steps:
  # Step 1: Building the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/googlegenai-0.0.1-SNAPSHOT', '.']

  # Step 2: Pushing the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/googlegenai-0.0.1-SNAPSHOT']

  # Step 3: Deploying the application to Kubernetes Engine
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'apply', '-f', 'kubernetes/deployment.yaml',
      '-f', 'kubernetes/service.yaml'
    ]
