steps:

  # Step 1: Building the Docker image
  - name: 'maven:3.8.3-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean','install']
 
 
 # Step 2: Run tests with coverage and generate coverage reports
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['test', 'jacoco:report']
    
  - name: 'gcr.io/suga-new01/sonar-scanner'
    args: ['sonar-scanner']
    
  # Step 4: Building the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gitsourcerepo/googlegenai-image:$SHORT_SHA', '.']
 
  # Step 5: Pushing the Docker image to artifact registry<<gitsourcerepo>> image name <<googlegenai-image>>
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gitsourcerepo/googlegenai-image:$SHORT_SHA']
 

