steps:
  # Step 1: Building the Docker image
  - name: 'maven:3.8.3-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']
  
  # Step 2: Building the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gitsourcerepo/googlegenai-image:$SHORT_SHA', '.']
 
  - name: gcr.io/cloud-builders/sonarscanner
    entrypoint: sonar-scanner
    args:
      - -Dsonar.projectKey=suganandan_googlegenai  # Replace with your SonarCloud project key
      - -Dsonar.organization=suganandan  # Replace with your SonarCloud organization
      - -Dsonar.sources=.  # Path to the source code
      - -Dsonar.host.url=https://sonarcloud.io  # Replace with the SonarCloud host URL
      - -Dsonar.login=suganandan@hotmail.com  # Replace with the SonarCloud authentication token
      - -Dsonar.java.binaries=target/classes  # Path to the compiled Java classes
      - -Dsonar.java.testBinaries=target/test-classes  # Path to the compiled Java test classes
      - -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info  # Path to the LCOV coverage report
      - -Dsonar.typescript.reportPaths=target/tscoverage.json  # Path to the TypeScript coverage report   
  # Step 3: Pushing the Docker image to artifact registry<<gitsourcerepo>> image name <<googlegenai-image>>
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gitsourcerepo/googlegenai-image:$SHORT_SHA']
 

