server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

genAi:
  projectId: suga-new01
  location: us-central1
  modelName: gemini-pro
  publisher: google
  latestModel: gemini-2.0-flash-exp

sum:
  temperature: 0.2
  tokens: 512
  topP: 0.2
  topK: 10  




